import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://practice.expandtesting.com/upload');
  await expect(page.getByRole('navigation', { name: 'Main navigation' })).toBeVisible();

  await page.getByText('Do you enjoy this platform? ❤️ Buy us a coffee Home File Uploader File Uploader').click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.getByTestId('file-input').click();
  await page.getByTestId('file-input').setInputFiles('manual testing.txt');
  await page.getByTestId('file-input').click();
  await expect(page.getByTestId('file-input')).toHaveValue('manual testing.txt');
  await page.getByText('Do you enjoy this platform? ❤️ Buy us a coffee Home File Uploader File Uploader').click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('Tab');
  await page.getByRole('link', { name: 'Home' }).press('Tab');
  await page.getByRole('link', { name: 'Automation testing software' }).press('Tab');
  await page.locator('#core').getByRole('link', { name: 'Software testing tools' }).press('Tab');
  await page.getByTestId('file-input').press('Tab');
  await page.getByTestId('file-submit').press('Enter');
  await page.getByTestId('file-submit').press('ControlOrMeta+-');
  await page.getByTestId('file-submit').press('ControlOrMeta+-');
  await page.getByTestId('file-submit').press('ControlOrMeta+-');
  await page.getByText('Do you enjoy this platform? ❤️ Buy us a coffee Home File Uploader File Uploader').click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.getByTestId('file-submit').click();
  await expect(page.getByRole('navigation', { name: 'Main navigation' })).toBeVisible();

  await page.getByRole('heading', { name: 'File Uploaded!' }).click();
  await expect(page.locator('h1')).toContainText('File Uploaded!');
});